parameters:
    db.host: mysql:host=localhost
    db.name: dbname=gsb
    db.user: root
    db.mdp: tixymcz
services:
    pg_gsb_frais.pdo:
        class: Pg\GsbFraisBundle\services\PdoGsb
        arguments: [%db.host%,%db.name%,%db.user%,%db.mdp%]

